apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver-statefulset
spec:
  serviceName: "sqlserver"
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-database
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: sql-password
          ports:
            - containerPort: 1433

